### ISSUE TITLE
Backport va_args spinel fixes from openthread

### ISSUE THREAD

**Issue by GiedriusM** [openthread/wpantund#15]
I have experienced problem when running spinel pack/unpack. On some platforms data is incorrectly processed, in others segmentation fault occurs.

Reference: https://github.com/openthread/openthread/pull/208

**Comment by darconeous** [comment]
Thanks for reminding me, I'll go ahead and get this ported over.

**Comment by darconeous** [comment]
Should be all fixed on master now.
