### ISSUE TITLE
script: wpanretian.sh seems out of date?

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/wpantund#171]
When restoring, the script complains:

>> wpanctl set Network:NodeType "end-device"
>> set failed with error 16. PropertyNotFound

**Comment by abtink** [comment]
Indeed. We should remove this later. The script should continue to work even with a property set error. Technically we don't need to retain the `NodeType`. It was originally saved for debugging purposes.

**Comment by abtink** [comment]
Added https://github.com/openthread/wpantund/pull/422 to address.

Please note that `wpanretain` feature is intended for use during development on NCP's not yet supporting non-volatile setting feature.

**Comment by jwhui** [comment]
Resolved by #422.
