### ISSUE TITLE
NCP's serial port

### ISSUE THREAD

**Issue by khn123** [openthread/wpantund#217]
Hello,
  I tried to build a Border Router with raspberry pi 3.  But it had an error with wpantund. 
![image](https://user-images.githubusercontent.com/29656445/29826949-f1e0d554-8cd8-11e7-8747-46805ebb962c.png)

Anyone know this probleme?
Thx,

**Comment by bukepo** [comment]
Is it possible to post this issue on https://groups.google.com/forum/#!forum/openthread-users? And it's easier for us to identify the problem if you share more details, such as the OpenThread firmware(version and how it is built), configuration file(/etc/wpantund.conf), wpantund version.
