### ISSUE TITLE
can't use openthread  Border router: Which NCP do i have to use ?

### ISSUE THREAD

**Issue by khn123** [openthread/wpantund#219]
Hi there , 
here is the message when a run wpantund . 

Aug 30 14:22:10 raspberrypi wpantund[1499]: SpinelNCPTask.cpp:85: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
Aug 30 14:22:10 raspberrypi wpantund[1499]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
Aug 30 14:22:10 raspberrypi wpantund[1499]: SendCommand task encountered an error: 7 (0x00000007)
Aug 30 14:22:10 raspberrypi wpantund[1499]: wpantund[1499]: SpinelNCPTask.cpp:85: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
Aug 30 14:22:10 raspberrypi wpantund[1499]: wpantund[1499]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
Aug 30 14:22:10 raspberrypi wpantund[1499]: wpantund[1499]: SendCommand task encountered an error: 7 (0x00000007)
Aug 30 14:22:10 raspberrypi wpantund[1499]: SpinelNCPInstance-Protothreads.cpp:412: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
Aug 30 14:22:10 raspberrypi wpantund[1499]: wpantund[1499]: SpinelNCPInstance-Protothreads.cpp:412: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboun...mLastHeader)
Aug 30 14:22:11 raspberrypi wpantund[1499]: Resetting and trying again... (retry 1)
Aug 30 14:22:11 raspberrypi wpantund[1499]: wpantund[1499]: Resetting and trying again... (retry 1)

>  My ncp is an KW41Z .  which firmware do i have to use to do the Job? 
> Which NCP is advised for this usage ?

Regards

**Comment by jwhui** [comment]
Closing stale issue.
