### ISSUE TITLE
Get wpantund up and running on OSS-Fuzz

### ISSUE THREAD

**Issue by darconeous** [openthread/wpantund#225]
With the fuzzing-related work on #224, #222, and #191 now coming together nicely, we should get a continuous fuzzing system in place. It just so happens that Google has [OSS-Fuzz](https://github.com/google/oss-fuzz), which at first glance looks like it would be easier to get set up and running compared to the alternatives.

**Comment by darconeous** [comment]
@jwhui, [OSS-Fuzz](https://github.com/google/oss-fuzz) this might be useful for OpenThread, too.

**Comment by jwhui** [comment]
@darconeous, OpenThread is already added to OSS-Fuzz :)

https://github.com/google/oss-fuzz/tree/master/projects/openthread

**Comment by darconeous** [comment]
Awesome!

I've got OSS-Fuzz working well on [my branch](https://github.com/darconeous/oss-fuzz/tree/wpantund-fuzz/projects/wpantund) on my local machine. Once #224 lands I'll file a pull request against OSS-Fuzz.

**Comment by darconeous** [comment]
Actual OSS-Fuzz pull request: https://github.com/google/oss-fuzz/pull/843

**Comment by darconeous** [comment]
https://github.com/google/oss-fuzz/pull/843 has been merged. Will close once I see it running.

**Comment by darconeous** [comment]
It is now up and running.
