### ISSUE TITLE
Both links to the documentation are dead

### ISSUE THREAD

**Issue by SG7** [openthread/wpantund#243]
The link below specifies two links which are dead.
https://github.com/openthread/wpantund/blob/141dc3c97cf098cc3ab97afd560bbe64e9deeae3/third_party/openthread/src/ncp/PROTOCOL.md

**Comment by jwhui** [comment]
Note that you are referencing a git-hash from Nov 28th, 2016.

You can find the latest Spinel protocol specification here: https://github.com/openthread/openthread/tree/master/doc
