### ISSUE TITLE
Network:NodeType cannot be set, wpanretain.sh attempts to do it

### ISSUE THREAD

**Issue by tomas-c** [openthread/wpantund#249]
Reading wpanretain.sh I can see that it attempts to set `Network:NodeType`.

When attempting to set that property wpantund prints:

```
wpantund[897]: set_property: key: "Network:NodeType"
wpantund[897]: set_property: key: "Network:NodeType"
wpantund[897]: set_property: Unsupported property "Network:NodeType"
```

Which is wrong, wpanretain.sh for attempting to set it or wpantund for not being able to do it?

**Comment by abtink** [comment]
It's really use-case dependent. Typically wpantund is used on a device expected to always be a Thread router. So we can consider removing "Network:NodeType" from `wpanretain.sh` script. It should be harmless as it is though.

I think the better approach for retaining network info is to use NCP itself. OpenThread has support for saving/recalling network info in non-volatile memory. The wpantund network retain feature was added before we had this feature in OpenThread as a (sort of temporary) alternate solution (mainly used for testing/debugging). `wpanretain` as is, cannot really save all info Thread operation recommends to be retained, like counters, child table, etc.
