### ISSUE TITLE
Invalid Neighbor during Join caused by unicast address in ncp

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/wpantund#277]
This is the WPANTUND side of these two issues:

https://github.com/openthread/openthread/pull/2579

https://github.com/openthread/openthread/issues/2571

In the end, the NCP is now rejecting addresses being sent to the NCP from wpantund
causing the WPANTUND to send a RESET command to the NCP...

From openthread pull request 2579 -

>> Feb 22 18:57:06 beaglebone wpantund[1344]: Adding on-mesh prefix "fd11:22::/64" to NCP
>> Feb 22 18:57:06 beaglebone wpantund[1344]: wpantund[1344]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
>> Feb 22 18:57:06 beaglebone wpantund[1344]: wpantund[1344]: SendCommand task encountered an error: 24 (0x00000018)
>> Feb 22 18:57:06 beaglebone wpantund[1344]: wpantund[1344]: Error NCPInvalidArgument (24) while performing "adding unicast address" on NCP - Resetting NCP.
>> Feb 22 18:57:06 beaglebone wpantund[1344]: Node type change: "unknown" -> "leader"
>> Feb 22 18:57:06 beaglebone wpantund[1344]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
>> Feb 22 18:57:06 beaglebone wpantund[1344]: SendCommand task encountered an error: 24 (0x00000018)
>> Feb 22 18:57:06 beaglebone wpantund[1344]: Error NCPInvalidArgument (24) while performing "adding unicast address" on NCP - Resetting NCP.
>> Feb 22 18:57:06 beaglebone wpantund[1344]: wpantund[1344]: Error Canceled (11) while performing "restoring on-mesh prefix" on NCP - Resetting NCP.
>> Feb 22 18:57:06 beaglebone wpantund[1344]: wpantund[1344]: State change: "associated" -> "uninitialized"
>> Feb 22 18:57:06 beaglebone wpantund[1344]: wpantund[1344]: Taking interface(s) down. . .
>> Feb 22 18:57:06 beaglebone wpantund[1344]: wpantund[1344]: NCPInstance: error 0

THIS is the reset

>> Feb 22 18:57:06 beaglebone wpantund[1344]: Error Canceled (11) while performing "restoring on-mesh prefix" on NCP - Resetting NCP.

>> Feb 22 18:57:06 beaglebone wpantund[1344]: State change: "associated" -> "uninitialized"

**Comment by DuaneEllis-TI** [comment]
Adding: @srickardti @pkanek so they are aware.

**Comment by abtink** [comment]
Submitted PR: https://github.com/openthread/wpantund/pull/279

**Comment by abtink** [comment]
https://github.com/openthread/wpantund/pull/279 is merged and should address this.

**Comment by abtink** [comment]
I think we can close this with the change from https://github.com/openthread/wpantund/pull/279

**Comment by abtink** [comment]
Closing this issue.
