### ISSUE TITLE
Form command should scan in order to pick optimal channel and PANID.

### ISSUE THREAD

**Issue by darconeous** [openthread/wpantund#36]
Currently, the form command is picking the PANID randomly. If a channel or channel mask is not specified, then channel 11 is assumed. If a channel mask with more than one channel is specified, then a channel is chosen randomly.

We should be doing a scan before doing a form to examine the characteristics of the RF environment to make sure that we pick appropriate values for the PANID and channel.

**Comment by abtink** [comment]
We are moving towards using Operational Dataset (and new OT API `otDatasetCreateNewNetwork()`) for "form" command and thus delegating the selection of network parameters (if not specified by user) to NCP/OpenThread. I think we should consider this as an enhancement in OpenThread. I am going to close this.
