### ISSUE TITLE
Keyboard and mouse freezing on Raspberry Pi 4

### ISSUE THREAD

**Issue by robertcragie** [openthread/wpantund#441]
**Describe the bug**
When running `wpantund` on a Raspberry Pi 4, it causes a USB-connected key board and mouse to freeze for approx 1 second every approx. 4 seconds. This makes user input very challenging. Note this does not happen on Raspberry Pi 3.

**To Reproduce**
Git commit id: 409b8c281
IEEE 802.15.4 hardware platform: Nordic PCA10056 1.1.0 connected as NCP through `/dev/ttyACM0`
Build steps: As per [openthread.io guide](https://openthread.io/guides/border-router/build)
Also exhibited using Docker image `openthread/otbr:latest`
Running `sudo systemctl stop wpantund.service` stops the freezing, so it is clearly caused by `wpantund`.

**Expected behavior**
wpantund should have no adverse effects on any additionally connected USB devices.

**Additional context**
Tried using powered USB hub, - made no difference.

**Comment by robertcragie** [comment]
There have been some issues raised regarding the USB host controller on the Raspberry Pi 4 and there is an update firmware for it (see https://www.raspberrypi.org/forums/viewtopic.php?t=250990). I tried this but it makes no difference.

**Comment by robertcragie** [comment]
I believe this is due to the JLink mass storage device. I disabled it and the problem seems to go away. I also do not see the problem using the PCA10059 dongle, which does not have a JLink and uses the nRF52840 USB interface directly.

**Comment by jwhui** [comment]
@robertcragie, great to hear you found a solution. Thanks for following up on this.

**/cc/** @LuDuda @Vyrastas keep this in mind for documentation purposes.
