### ISSUE TITLE
The wiki is missing.

### ISSUE THREAD

**Issue by TPolzer** [openthread/wpantund#447]
The README says:
"For more information, see the wiki: https://github.com/openthread/wpantund/wiki"
But the github project seems to be set up without a wiki?

**Comment by abtink** [comment]
@TPolzer Thanks for raising the issue. 
Submitted https://github.com/openthread/wpantund/pull/449 to update the link to [openthread.io](https://openthread.io/) guide/codelab.

**Comment by abtink** [comment]
Addressed by https://github.com/openthread/wpantund/pull/449
