### ISSUE TITLE
routertable eui64 does not match..

### ISSUE THREAD

**Issue by slaesh** [openthread/wpantund#476]
hey all! 
I am wondering how to read those ext-adrresses.. Trying to follow it in the code, but its kinda hard..

![image](https://user-images.githubusercontent.com/55546823/100229934-430aaa80-2f25-11eb-9e66-d4053faf1f82.png)

None of those (first values in the table) UID's are known by me and doesnt look like the UID's of my chips..

How, where and why are these values transformed?

Thanks! :)

**Comment by jwhui** [comment]
The IEEE 802.15.4 Extended Address and IEEE EUI-64 are not the same. The former is what Thread devices use in IEEE 802.15.4 MAC frames during normal operation. Thread 1.1.1 Section 3.2 states the following:

> The specific value provided by the device to the MAC sublayer to represent the aExtendedAddress MUST be a random generated 64-bit value different from the universally administered IEEE EUI-64 value that has been factory assigned to the Thread interface.

**Comment by slaesh** [comment]
Oh, I see! Thanks for your quick and awesome response :star_struck: 

I am wondering how to identify devices in my network. I am trying to build an application based on a borderrouter and wpantund/wpanctl.
BUT .. Imagine I am now joining a new device via the commissioner, by its EUI-64.

`wpanctl commissioner start`

and

`wpanctl commissioner joiner-add 0011223344556677 120 COOLES_PW`

After that.. HOW will I get notified that the device is actually joined and which address this device got? The device itself has no HMI or anyhting..

Kinda stuck right now in this scenario..

**Comment by jwhui** [comment]
> After that.. HOW will I get notified that the device is actually joined and which address this device got? The device itself has no HMI or anyhting..

@slaesh , I suggest that your application protocol provide this functionality.

**Comment by jwhui** [comment]
Closing stale issue.
