### ISSUE TITLE
Unit wpantund.service could not be found.

### ISSUE THREAD

**Issue by hansdeweerd** [openthread/wpantund#488]
I am trying to set up a thread network with a raspberry pi model 4b and a wireless starting kit(brd4001A) with a brd4161A on it as an NCP, this needs to be the border router.

but de wpantund is not showing up as a service. I follow this instruction: https://openthread.google.cn/certification/border-router/device-setup. for the NCP i have used the following build configurations: BORDER_AGENT=1 BORDER_ROUTER=1 COMMISSIONER=1 UDP_FORWARD=1 

also, the config file was not installed so I installed wpantund by hand. and edit the config file to Config:NCP:SocketPath '/dev/ttyACM0'

**Comment by jwhui** [comment]
@hansdeweerd , the main branch in openthread/ot-br-posix implements the [RCP model](https://www.youtube.com/watch?v=EDseO8GY9Cg) and does not use `wpantund`.

If you would like to follow the Border Router Guide, try using the [wpantund/master branch](https://github.com/openthread/ot-br-posix/tree/wpantund/master) in openthread/ot-br-posix.

**Comment by hansdeweerd** [comment]
thank you for your reply @jwhui 

how can I install that repository?

**Comment by jwhui** [comment]
`./script/setup` should invoke [`script/_wpantund`](https://github.com/openthread/ot-br-posix/blob/wpantund/master/script/_wpantund), which installs `wpantund`.

**Comment by hansdeweerd** [comment]
thanks it works!
