### ISSUE TITLE
removing devices from a thread network.

### ISSUE THREAD

**Issue by hansdeweerd** [openthread/wpantund#493]
how can I remove a device from a thread network, and is this also possible to do this from the border router?

**Comment by abtink** [comment]
In `wpantund` the `wpanctl` command `leave` (and its realted DBUS API) will cause device to leave its current network.

**Comment by hansdeweerd** [comment]
yes, I understand. but I mean that you can remove a sleepy node from the network by giving the border router a command to remove it, is that possible?

**Comment by abtink** [comment]
I don't think it is possible within Thread spec.

If the "Mac Filter (allow-list/deny-list)" is supported on BR device, the `AllowList/DenyList` can be used to disallow BR to talk to a particular device (which causes it to get detached).

**Comment by abtink** [comment]
`wpantund` provides a bunch of properties that can be used to control `Mac::Filter`.
https://github.com/openthread/wpantund/blob/820468161c87816a3e94366ebbe2a932650416e3/src/wpantund/wpan-properties.h#L202-L208
