### ISSUE TITLE
Bidirectional IPv6 reachability between Thread and Ethernet/Wi-Fi

### ISSUE THREAD

**Issue by hansdeweerd** [openthread/wpantund#496]
Bidirectional IPv6 reachability between Thread and Ethernet/Wi-Fi without having to switch to an RCP, and open thread daemon.

**Comment by jwhui** [comment]
`wpantund` provides a standard IPv6 network interface. To enable IPv6 reachability between Thread and other network interfaces, you need to configure a routable IPv6 prefix for each network and establish routes between them. The latest main branch of [openthread/ot-br-posix](https://github.com/openthread/ot-br-posix) includes mechanisms to do this automatically, but also relies on the RCP.
