### ISSUE TITLE
joiner -e <psk> fails on NCP firmware 

### ISSUE THREAD

**Issue by primis** [openthread/wpantund#498]
**Describe the bug**
When attempting to run joiner -e <PSK> inside wpanctl, on NCP firmware, an error is thrown stating THREAD_JOINER is not supported by NCP

**To Reproduce**
Information to reproduce the behavior, including:
1. Git commit id: https://github.com/openthread/wpantund/commit/820468161c87816a3e94366ebbe2a932650416e3
2. Hardware platform: NRF52840-DK running NCP version "OPENTHREAD/20191113-00867-gd81d769e; NRF52840; Jun 16 2020 17:25:12"

**Expected behavior**
joiner -e <PSK> Should join a network that is able to be joined

**Console/log output**
wpanctl:wpan0> joiner -e J01NUS
Starting joiner commissioning, PSKd:"J01NUS" ...
Failed to start Joiner Commissioning - error 16. PropertyNotFound
Error 16 (0x10)
wpanctl:wpan0> joiner -s
Joiner:State: Capability THREAD_JOINER (required for "Joiner:State") is not supported by NCP (14)
Error 14 (0x0E)

**Comment by abtink** [comment]
`Capability THREAD_JOINER (required for "Joiner:State") is not supported by NCP (14)`

@primis , this error log already indicates the issue 😃  that the NCP firmware build that is being used does not support/enable the "joiner" feature (the config was not enabled on the build). Therefore `wpantund` does not support the joiner related properties/commands. 

This is enabled on OT build by config `OPENTHREAD_CONFIG_JOINER_ENABLE`. You can see the autoconf/cmake options `OT_JOINER` in [openthread/README](https://github.com/openthread/openthread/blob/71e6543d9b207a8d06509ffeef6c276fb3f5dc2f/examples/README.md).
