### ISSUE TITLE
brew install for OSX no formulae exists

### ISSUE THREAD

**Issue by afuen010** [openthread/wpantund#514]
**Describe the bug**
Following the instructions for installation on MacOSX Monterrey 12.5.1. Running the brew install ./etc/wpantund.rb command results in the following output from brew. 
brew install ./etc/wpantund.rb
Warning: No available formula or cask with the name "./etc/wpantund.rb".

Searching for the formulae on brew shows no results. Is this even available on brew anymore?

**Comment by abtink** [comment]
Short answer is no.
In general, `wpantund` on MAC OS X was experimental since beginning. I would personally recommend use on Ubuntu (linux) only.
