### ISSUE TITLE
DBUSIPCServer.cpp

### ISSUE THREAD

**Issue by sudharshanredd** [openthread/wpantund#63]
when i am configuring wpantund-master i was getting error at DBUSIPCServer.cpp:93:Requiremet Failed(Connection ":1.74" is not allowed to own the service "com.nestlabs.WPANTunnelDriver" due to security policies in the configuration file).

Steps following to configure:
./bootstrap.sh
./configure --sysconfdir=/etc
make

when i am going to compile wpantund it is throwing error like DBUSIPCServer.cpp.
can you please look into the issue and give some information to overcome this issue.
(NOTE: DBUSIPCServer.cpp error is getting only in laptop's )

Thanks,
Sudharshan.
![screenshot from 2016-09-23 19-00-49](https://cloud.githubusercontent.com/assets/22396233/18789069/233aef0e-81c7-11e6-997c-708f6734a086.png)

**Comment by darconeous** [comment]
The default `sysconfdir` should be `/etc`, even if you don't specify it directly. So if you install it where it should be, you should be all set.

That being said, sometimes D-Bus seems to get into a weird state where it starts behaving like this. A reboot seems to fix it. Worth a try.

You didn't mention what your specific build error was on your laptop. Mind pasting it in?

**Comment by darconeous** [comment]
Closing. Please re-open if you can provide more details.
