### ISSUE TITLE
SPINEL_PROP_NET_STACK_UP Definition Comment Incorrect

### ISSUE THREAD

**Issue by nibanks** [openthread/wpantund#84]
I am working on adding Spinel/NCP support to Windows and I noticed the comment here:

`SPINEL_PROP_NET_STACK_UP         = SPINEL_PROP_NET__BEGIN + 2, ///< [C]`

I am pretty sure the `[C]` is supposed to be `[b]` just like `SPINEL_PROP_NET_IF_UP`.

**Comment by abtink** [comment]
Yes. Indeed.

**Comment by darconeous** [comment]
I need to remove those comments.

It would probably be best to use the official Spinel protocol docs.

**Comment by darconeous** [comment]
I think this has been fixed.
